### PR TITLE
Fantasy console theming

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by micahlt** [comment]
Might be worth clarifying what exactly the theme of the interface should be.  What I came up with was less fantasy console-based and closer to Muse.  I'm open to either one, but no sense in either of us wasting time 😄

**Comment by maxwofford** [comment]
@micahlt 100%! do you have any code from the preview showed in #gamelab-dev? I love how it looked & if I can use/merge it into what i'm doing that'd really help

**Comment by micahlt** [comment]
> @micahlt 100%! do you have any code from the preview showed in #gamelab-dev? I love how it looked & if I can use/merge it into what i'm doing that'd really help

I unfortunately don't.  That's just a mockup I made in Affinity Designer, not actual code.  If I could spin up the code that fast I'd have already submitted a PR 😂

**Comment by maxwofford** [comment]
I just got through rebasing this with main. @leomcelroy could we either merge this to main, or promote this to the new `dev` branch that everything else will merge into before a release bump?

**Pull request merged**
